config/routes.rb
Rails.application.routes.draw do
  resources :givings, only:[:show]
  resources :adoptions, only:[:show]
  resources :pets
  resources :stores
  resources :users
  root :to => "stores#index"
  get 'sessions/new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/storepets' => 'pets#pet'
  # get '/dogs' => 'pets#dog'
  # get '/rabbits' => 'pets#rabbit'
  # get '/hamsters' => 'pets#hamster'

  post '/adoption' => 'pets#adoption', as: "adoption_pet"

  get '/giving_new' => 'pets#giving_new', as: "new_giving"
  get '/giving_existing' => 'pets#giving_existing', as: "new_existing"

  post '/change_status' => 'pets#change_status', as: "change_status"

  get '/tips' => 'stores#tips', as: "tips"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :pet, :class_name => "Pet"
  belongs_to :adoptor, :class_name => "User"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/giving.rb
class Giving < ApplicationRecord
  belongs_to :pet, :class_name => "Pet"
  belongs_to :giver, :class_name => "User"
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :store
  has_many :adoptions
  has_many :givings
  has_many :givers, :class_name => "User", through: :givings
  has_many :adoptors, :class_name => "User", through: :adoptions


end

app/models/store.rb
class Store < ApplicationRecord
  has_many :pets
end

app/models/user.rb
class User < ApplicationRecord
  has_many :adoptions, :foreign_key => 'adoptor_id'
  has_many :givings, :foreign_key => 'giver_id'
  has_many :adoptor_pets, through: :adoptions, :source => :pet
  has_many :giver_pets, through: :givings, :source => :pet
  has_secure_password
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController


  def show
    @adoption = Adoption.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # protect_from_forgery with: :exception, prepend: true
    include SessionsHelper

    def tips

    end

end

app/controllers/givings_controller.rb
class GivingsController < ApplicationController
  def new
    @giving = Giving.new
  end

  def show
    @giving = Giving.find(params[:id])
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  include SessionsHelper
  before_action :authorized, only:[:index, :new]

  def index
    @pets = Pet.all
  end

  def giving_new
    @pet = Pet.new
    render :_form
  end

  def giving_existing
    @pets = current_user.adoptor_pets.where(status: false)
    @pet = Pet.new
    render :_giving
  end

  def change_status
    params[:pet][:id].each do |id|
      if id != ""
        Pet.find(id).update(status: true)
        Giving.create(giver_id: session[:user_id], pet_id: id, giving_date: Time.now)
      end
    end
    redirect_to user_path(current_user)
  end

  def pet
    @store = Store.find(session[:store_id])
    @pets = @store.pets.all.select{|pet| pet.animal_type == params[:type] && pet.status == true}
  end

  def create
    @pet = Pet.new(sub_params)
    # @pet.giver_id = session[:user_id]
    @pet.store_id = session[:store_id]
      if @pet.save
        @giving = Giving.create(giver_id: session[:user_id], pet_id: @pet.id, giving_date: Time.now)
        redirect_to user_path(@giving.giver)
      else
        render 'new'
      end
  end

  def show
    @pet = pet_find
    @user = User.find(session[:user_id])
  end

  def adoption
    @pet = Pet.find(params[:pet_id])
    if session[:user_id]
      @pet.store_id = session[:store_id]
      @pet.status = false
      @pet.save
      @adoption = Adoption.create!(adoptor_id: session[:user_id], pet_id: @pet.id, adoption_date: Time.now)
      @user = @adoption.adoptor
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def edit
    @pet = pet_find
  end

  def update
    @pet = pet_find
      if @pet.update(sub_params)
        redirect_to pet_path(@pet)
      else
        render 'edit'
      end
  end

  def destroy
    @pet = pet_find
    @pet.destroy
      redirect_to stores_path
  end

  private

  def sub_params
    params.require(:pet).permit(:name, :animal_type, :breed, :age, :gender, :store_id)
  end

  def pet_find
    Pet.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create

    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      # session[:id] = User.find_or_create_by(name: params[:name]).id
      redirect_to stores_path
    else
      flash[:notice] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    log_out
    redirect_to stores_path
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController


  def index
    @stores = Store.all
  end

  def tips

  end

  def show
    @store = Store.find(params[:id])
    session[:store_id] = @store.id
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(sub_params)
      if @user.save
        log_in @user
        session[:user_id] = @user.id
        flash[:success] = "Welcome to our store"
        redirect_to stores_path
      else
        render 'new'
      end
  end

  def show
    @user = user_find
    @pets = @user.adoptor_pets.where(status: false)
    @uniq_pet = @pets.uniq
  end

  def edit
    @user = user_find
  end

  def update
    @user = user_find
      if @user.update(sub_params)
        redirect_to user_path(@user)
      else
        render 'edit'
      end
  end

  def destroy
    @user = user_find
    @user.destroy
      redirect_to stores_path
  end

  private

  def sub_params
    params.require(:user).permit(:name, :password)
  end

  def user_find
    User.find(params[:id])
  end
end

app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/givings_helper.rb
module GivingsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authorized
    unless logged_in?
      flash[:notice] = "Please login to see this page"
      redirect_to login_path
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adoptions/show.html.erb
<h1>Adoption</h1>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Ultra" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#d0ede0;">
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container-login200" style="background-image: url( <%= asset_path('bg-03.jpg') %>);">
  <div class="row">
  <div class="col-sm-12">
      <h1 class="branch">Giving Pet Form</h1>

 <br>

    <div class="form-login box text-center">


            <%= form_for @pet do |f| %>
                <div class="form-group">
                  <%= f.text_field :name, autofocus: true, placeholder:"Name",class:"form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label "Animal Type"%>
                  <%= f.select("animal_type", ["Cat", "Dog", "Rabbit", "Hamster"]) %>
                </div>

                <div class="form-group">
                  <%= f.text_field :breed, placeholder:"Breed",class:"form-control" %>
                </div>

                <div class="form-group">
                  <%= f.text_field :age, placeholder:"Age",class:"form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :gender%>
                  <%= f.select("gender", ['Male', 'Female']) %><br>
                </div>



                <div class="actions">
                  <%= f.submit "give",class:"btn btn-lg btn-elegant" %>
                </div>
              <% end %>
</div>
          </div>
  </div>
          </div>

app/views/pets/_giving.html.erb
<div class="container text-center petform">
  <div >
    <h1 class="branch">Giving Your Adopted pets back to Store</h1>
  </div>
<br>
<div class="container text-center">
<% if @pets.empty? %>
<h3>You Don't have any Pets that Adopted from our store</h3><br>
<h3>Wanna Adopt some?</h3>
<br>
<br>
<%= button_to "Adopt Pets", pets_path, {method: "get", class:'btn btn-elegant'} %>


<% else %>

  <%= form_for(@pet, :url => change_status_path) do |f| %>
  <%= f.collection_check_boxes(:id, @pets, :id, :name ) do |b| %>
  <div class="inputGroup ">

    <%= b.check_box %>
    <%= b.label(:name => b.value)  %>
  </div>



  <%end%>

<%= f.submit "Giving Pet",class: "btn btn-elegant" %>
<% end %>
<% end %>

<br>
<div class="middle_link">
<%= link_to "Back to Store page", stores_path %>
</div>
</div>
</div>

app/views/pets/index.html.erb
<div class="container" id="choose_pet">
<div class="row">
      <div class="col-sm-3 ">
            <div class="card card-cascade text-center">
                <!-- Product Image -->
                <div class="product-img">
                    <%= image_tag ("choose_cat.jpg") %>
                </div>
                <div class="product-description">
                    <%= link_to "Cat", storepets_path(:type=>"Cat"),:class=>"btn btn-elegant" %>
                </div>
            </div>
        </div>

        <div class="col-lg-3 text-center">
              <div class="card card-cascade text-center">
                  <!-- Product Image -->
                  <div class="product-img">
                      <%= image_tag ("choose_dog.jpg") %>
                  </div>
                  <div class="product-description">
                      <%= link_to "Dog", storepets_path(:type=>"Dog"),:class=>"btn btn-elegant" %>
                  </div>
              </div>
          </div>

          <div class="col-lg-3 text-center">
                <div class="card card-cascade text-center">
                    <!-- Product Image -->
                    <div class="product-img">
                        <%= image_tag ("choose_rabbit.jpg") %>
                    </div>
                    <div class="product-description">
                        <%= link_to "Rabbit", storepets_path(:type=>"Rabbit"),:class=>"btn btn-elegant" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 text-center">
                  <div class="card card-cascade text-center">
                      <!-- Product Image -->
                      <div class="product-img">
                          <%= image_tag ("choose_hamster.jpg") %>
                      </div>
                      <div class="product-description">
                        <%= link_to "Hamster", storepets_path(:type=>"Hamster"),:class=>"btn btn-elegant" %>
                      </div>
                  </div>
              </div>


  </div>
</div>

app/views/pets/new.html.erb
<div class="container-login300 text-center" style="background-image: url( <%= asset_path('bg-05.jpg') %>);">
<div class="middle2">

<h1> Is the pet previously adopted from our store? </h1>
<br>
  <div class="boolean">
  <%= button_to "Yes", new_existing_path , {method: :get,:class=>"btn btn-blue-grey waves-effect btn-lg"} %>
  <br>
  <%= button_to "No", new_giving_path, {method: :get,:class=>"btn btn-blue-grey waves-effect btn-lg"} %>
  </div>
</div>
</div>

app/views/pets/pet.html.erb
<div id="demotext">
  <br>
  <h1 class="text-center branch top">Pet Adoption List</h1>
  <br>
</div>
<div class="container">
<div class="row ">
     <% @pets.each do |pet| %>
                            <!-- Single Product -->
                            <div class="col-sm-4 text-center">
                                <div class=" card card-cascade text-center">
                                    <!-- Product Image -->
                                    <div class="product-img">
                                      <% if pet.image %>
                                      <a href=<%= "pets/#{pet.id}" %>>
                                        <%= image_tag (pet.image) %>
                                          </a>
                                          <% else %>
                                        <p>  This pet has no pics right now</p>
                                        <% end %>

                                    </div>

                                    <!-- Product Description -->
                                    <div class="product-description">
                                        <span><%= pet.age %> years old</span>
                                        <a href=<%= "pets/#{pet.id}" %>>
                                            <h6><%= pet.name %></h6>
                                        </a>
                                        <br>
                                        <!-- <p class="product-price"><%= pet.gender %></p> -->

                                        <!-- Hover Content -->

                                    </div>
                                </div>
                            </div>

<% end %>
      <div class="container text-center">
      <%= link_to "Adopt Different Pets", pets_path,class:'btn btn-big btn-primary' %>
      </div>
</div>
</div>

app/views/pets/show.html.erb
<div class="container" id="show_pet">
<div class="row">
<div class="col-lg-8 text-center ">
  <% if !@pet.image %>
   Picture is not available
  <% else %>
<%= image_tag (@pet.image) %>
<% end %>
</div>
<div class="col-lg-4 text-center">
<h1><%= @pet.name %></h1>

<hr>
<span><%= @pet.age %> Years Old</span>
<hr>
<p>Breed: <%= @pet.breed %></p>
<hr>
<p><%= @pet.gender %></p>
<hr>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
        <% if @pet.status == true %>
        <%= button_to "Adopt this Pet", adoption_pet_path, {method: :post,class:'btn btn-elegant', params:{pet_id:@pet.id}} %>
        <% else %>
        <%= "This pet has been adopted by #{@pet.adoptors.last.name}"%>
        <% end %>
        </div>
        <div class="col-sm-6">
        <%= link_to "Adopt Other Pets", pets_path,class:'btn btn-elegant' %>
      </div>
     </div>
    </div>
</div>
</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-inverse " style="height:48px;" >
  <a class="navbar-brand" href="#">J.T.S Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav" id="nav_left">
      <li class="nav-item">
        <a class="nav-link" href="/stores">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branch
        </a>
        <div class="dropdown-menu text-center" id="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/stores/1">Queens</a>
          <a class="dropdown-item" href="/stores/2">Manhattan</a>
          <a class="dropdown-item" href="/stores/3">Long Island</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tips">Tips</a>
      </li>
  </ul>
  <ul class="navbar-nav navbar-right ml-md-auto">

      <% if !current_user %>
      <li><a  class="nav-item " href="/users/new">Sigup</a></li>
      <li><%= link_to "Login", login_path, { method: :get,:class=>"nav-item" }%>
      <% else %>
      <li><%= link_to "Hello #{current_user.name}", current_user %></li>
      <li><%= link_to "Logout", logout_path, method: :delete %>
</li>
      <% end %>
  </ul>
  </div>
</nav>

app/views/stores/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" id="cover">
    <div class="carousel-item active">
      <img class="d-block w-100 p1" src="assets/home_1.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block text1">
        <div class="welcome message">
          <h3>Welcome to J.T.S Store</h3>
        </div>
        <div class="login">
          <h4>Please Take Me Home</h4>
            <br>
          <%= button_to "Join us", new_user_path, {method: :get,:class=>"btn btn-blue-grey waves-effect btn-lg"}%>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 p1" src="assets/home_2.jpg" alt="Second slide">
      <div class="carousel-caption d-none d-md-block text1">
        <div class="welcome message">
          <h3>Welcome to J.T.S Store</h3>
        </div>
        <div class="login">
          <h4>Please Take Me Home</h4>
          <br>
          <%= button_to "JOIN US", new_user_path,  {method: :get,:class=>"btn btn-blue-grey waves-effect btn-lg"}%>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 p1" src="assets/home_3.jpg" alt="Third slide">
      <div class="carousel-caption d-none d-md-block text1">
        <div class="welcome message">
          <h3>Welcome to J.T.S Store</h3>
        </div>
        <div class="login">
          <h4>Please Take Me Home</h4>
            <br>
          <%= button_to "Join us", new_user_path,  {method: :get,:class=>"btn btn-blue-grey waves-effect btn-lg"}%>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/stores/show.html.erb
<section class="home-video-area" id="about">
      <div class="container-fluid">
        <div class="row justify-content-end align-items-center text-center">
          <div class="col-lg-4 no-padding video-right">
            <p class="top-title"><%= "#{@store.branch_name}" %></p>
            <h1>
            Mission</h1>
            <p><span>We are a nonprofit organization that finds homes for abandoned cats and dogs throughout the Tri-State area, and provides behavior intervention when needed to improve chances of adoption.  Founded in 2018,  We also provide programs that enhance the bond between animals and people.</span></p>

            <div class="col-sm-6">
          <%= button_to "Adopt a Pet", pets_path, {method: "get",class:'btn btn-elegant'} %>
            </div>
            <div class="col-sm-6">
          <%= button_to "Give a Pet", new_pet_path, {method: "get",class:'btn btn-elegant'} %>
            </div>
          </div>
          <section class="video-area col-lg-6">

   <iframe width="560" height="315" src="https://www.youtube.com/embed/Xpnvug7Uwg8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

          </section>



        </div>
      </div>
    </section>
    <!-- End home-aboutus Area -->

app/views/stores/tips.html.erb
<div class="container"><h1 class="middle top">Tips for the First 30 Days of Dog Adoption</h1>

<p class="middle">The first few days in your home are special and critical for a pet. Your new dog will be confused about where he is and what to expect from you. Setting up some clear structure with your family for your dog will be paramount in making as smooth a transition as possible.</p>
<p class="middle"><strong>Before You Bring Your Dog Home:</strong></p>
<ul>
  <li>Determine where your dog will be spending most of his time. Because he will be under a lot of stress with the change of environment (from shelter or foster home to your house), he may forget any housebreaking (if any) he’s learned. Often a kitchen will work best for easy clean-up.</li>
  <li>If you plan on crate training your dog, be sure to have a crate set-up and ready to go for when you bring your new dog home. Find out more about craft training your dog</li>
  <li>Dog-proof the area where your pooch will spend most of his time during the first few months. This may mean taping loose electrical cords to baseboards; storing household chemicals on high shelves; removing plants, rugs, and breakables; setting up the crate, and installing baby gates.</li>
  <li>Training your dog will start the first moment you have him. Take time to create a vocabulary list everyone will use when giving your dog directions. This will help prevent confusion and help your dog learn his commands more quickly. Not sure which commands to use? Check out how to talk to your dog.</li>
  <li>Bring an ID tag with your phone number on it with you when you pick up your dog so that he has an extra measure of safety for the ride home and the first few uneasy days. If he is microchipped, be sure to register your contact information with the chip’s company, if the rescue or shelter did not already do so.</li>
</ul>

<p class="middle"><strong>First Day:</strong></p>
<ul>
  <li>We know moving is stressful — and your new dog feels the same way! Give him time to acclimate to your home and family before introducing him to strangers. Make sure children know how to approach the dog without overwhelming him. Go here for more on </li>
  <li>When you pick up your dog, remember to ask what and when he was fed. Replicate that schedule for at least the first few days to avoid gastric distress. If you wish to switch to a different brand, do so over a period of about a week by adding one part new food to three parts of the old for several days; then switch to half new food, half old, and then one part old to three parts new. For more information about your dog’s diet, check out our section on </li>
  <li>On the way home, your dog should be safely secured, preferably in a crate. Some dogs find car trips stressful, so having him in a safe place will make the trip home easier on him and you.</li>
  <li>Once home, take him to his toileting area immediately and spend a good amount of time with him so he will get used to the area and relieve himself. Even if your dog does relieve himself during this time, be prepared for accidents. Coming into a new home with new people, new smells and new sounds can throw even the most housebroken dog off-track, so be ready just in case. Need more housetraining tips? Check out our </li>
  <li>If you plan on crate training your dog, leave the crate open so that he can go in whenever he feels like it in case he gets overwhelmed. Also, be sure to check out the do’s and don’ts of </li>
</ul>

<div class="middle_link">
<%= link_to "Back to Home Page", stores_path%><br>
<%= link_to "Log out", logout_path, method: :delete%>

</div>
</div>

app/views/users/new.html.erb
<!-- <div class="container">    <h1>Create new user</h1>

<%= form_for @user do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %><br>
 <br>
 <%= f.label :password %>
 <%= f.text_field :password %> "Min 1 Character"<br>
 <br>
 <%= f.label :email %>
 <%= f.email_field :email %>
 <%= f.submit %>
<% end %>
</div> -->


	<div class="limiter">
		<div class="container-login100" style="background-image: url( <%= asset_path('bg-02.jpg') %>);">
			<div class="wrap-login100">
			<%= form_for @user do |f| %>
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape" style="content: url( <%= asset_path('logo.jpg') %>); height: 130px; weight: 130px"></i>
					</span>
					<br>
					<span class="login100-form-title p-b-34 p-t-27">
						J.T.S
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<%= f.text_field :name, class: "input100", placeholder: "username"%>
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<%= f.password_field :password, class: "input100",placeholder: "password" %>
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="container-login100-form-btn">
					<%= f.submit "Sign Up", class: "login100-form-btn" %>
					<% end %>
					</div>
				</form>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<div class="container text-center">
<h1 class="top branch">Welcome <%= @user.name%></h1>

<h3 class="h3 top">Adoption List</h3>
<table style="width:100%">
  <thead class="black-white-text">
    <tr>
      <th>Pet Name</th>
      <th>Pet Type</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Store</th>
      <th>Status</th>
    </tr>
  </thead>
<% @uniq_pet.each do |pet| %>
<tr>
  <td><%= pet.name %></td>
  <td><%= pet.animal_type %></td>
  <td><%= pet.age %></td>
  <td><%= pet.gender %></td>
  <td><%= pet.store.branch_name %></td>
  <td><%= "You have adopted #{pet.name} at #{pet.adoptions.last.adoption_date}" %></td>
</tr>
  <% end %>
</table>
<br>
<br>
<h3 class="h3">Given List</h3>
<table style="width:100%">
  <thead class="black-white-text">
    <tr>
      <th>Pet Name</th>
      <th>Pet Type</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Store</th>
      <th>Status</th>
    </tr>
  </thead>
<% @user.giver_pets.each do |pet| %>

<tr>
  <td><%= pet.name %></td>
  <td><%= pet.animal_type %></td>
  <td><%= pet.age %></td>
  <td><%= pet.gender %></td>
  <td><%= pet.store.branch_name %></td>
  <% if pet.adoptors.last && pet.adoptors.last != current_user  %>
  <td><%= "#{pet.adoptors.last.name} adopted #{pet.name} at  #{pet.adoptions.last.adoption_date}" %></td>
  <% else %>
  <td><%= "You have given #{pet.name} at #{pet.givings.last.giving_date}" %></td>
  <% end %>
</tr>
<% end %>
</table>

<div class="middle_link">
<%= link_to "Back to Home Page", stores_path%><br>


</div>
</div>